FROM python:3.11-slim

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install curl so Python can use it
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
# Copy your Flask app
COPY . .

# Expose Flask port
EXPOSE 5000

# Run Flask API (replace app.py with your actual filename)
CMD ["python", "app/app.py"]
